export function useGeo(currentLang) {
  const countryName = (code) =>
    geo.countries[code]?.[currentLang.value] ?? code

  const cityName = (id) =>
    geo.cities[id]?.[currentLang.value] ?? id

  return { countryName, cityName }
}

export const geo = {
  countries: {
    GBR: { it: "Regno Unito", en: "United Kingdom" },
    FRA: { it: "Francia", en: "France" },
    ESP: { it: "Spagna", en: "Spain" },
    USA: { it: "Stati Uniti", en: "United States" },
    ARE: { it: "Emirati Arabi Uniti", en: "United Arab Emirates" },
    EGY: { it: "Egitto", en: "Egypt" },
    GRC: { it: "Grecia", en: "Greece" },
    JPN: { it: "Giappone", en: "Japan" },
    MLT: { it: "Malta", en: "Malta" },
    TUR: { it: "Turchia", en: "Turkey" },
    MDV: { it: "Maldive", en: "Maldives" },
    DEU: { it: "Germania", en: "Germany" },
    DNK: { it: "Danimarca", en: "Denmark" },
    SWE: { it: "Svezia", en: "Sweden" },
    CZE: { it: "Repubblica Ceca", en: "Czech Republic" },
    NLD: { it: "Paesi Bassi", en: "Netherlands" },
    AUT: { it: "Austria", en: "Austria" },
    PRT: { it: "Portogallo", en: "Portugal" },
    IRL: { it: "Irlanda", en: "Ireland" },
    BEL: { it: "Belgio", en: "Belgium" },
    MAR: { it: "Marocco", en: "Morocco" },
    HUN: { it: "Ungheria", en: "Hungary" },
    ROU: { it: "Romania", en: "Romania" },
    POL: { it: "Polonia", en: "Poland" },
    FIN: { it: "Finlandia", en: "Finland" },
    NOR: { it: "Norvegia", en: "Norway" },
    THA: { it: "Thailandia", en: "Thailand" },
    CUB: { it: "Cuba", en: "Cuba" },
    KOR: { it: "Corea del Sud", en: "South Korea" },
    AUS: { it: "Australia", en: "Australia" },
    ISL: { it: "Islanda", en: "Iceland" },
    HRV: { it: "Croazia", en: "Croatia" },
    BGR: { it: "Bulgaria", en: "Bulgaria" },
    SRB: { it: "Serbia", en: "Serbia" },
    SVN: { it: "Slovenia", en: "Slovenia" },
    SVK: { it: "Slovacchia", en: "Slovakia" },
    EST: { it: "Estonia", en: "Estonia" },
    LVA: { it: "Lettonia", en: "Latvia" },
    LTU: { it: "Lituania", en: "Lithuania" },
    LUX: { it: "Lussemburgo", en: "Luxembourg" },
    SMR: { it: "San Marino", en: "San Marino" },
    CHE: { it: "Svizzera", en: "Switzerland" },
    BIH: { it: "Bosnia ed Erzegovina", en: "Bosnia and Herzegovina" }
  },

  cities: {
    Londra: { it: "Londra", en: "London" },
    Parigi: { it: "Parigi", en: "Paris" },
    Barcellona: { it: "Barcellona", en: "Barcelona" },
    "New York": { it: "New York", en: "New York" },
    Dubai: { it: "Dubai", en: "Dubai" },
    Sharm: { it: "Sharm", en: "Sharm" },
    Mykonos: { it: "Mykonos", en: "Mykonos" },
    Tokyo: { it: "Tokyo", en: "Tokyo" },
    Corfu: { it: "Corfù", en: "Corfu" },
    Ibiza: { it: "Ibiza", en: "Ibiza" },
    Santorini: { it: "Santorini", en: "Santorini" },
    Malta: { it: "Malta", en: "Malta" },
    Tenerife: { it: "Tenerife", en: "Tenerife" },
    Istanbul: { it: "Istanbul", en: "Istanbul" },
    Maldive: { it: "Maldive", en: "Maldives" },
    Berlino: { it: "Berlino", en: "Berlin" },
    Copenaghen: { it: "Copenaghen", en: "Copenhagen" },
    Stoccolma: { it: "Stoccolma", en: "Stockholm" },
    Praga: { it: "Praga", en: "Prague" },
    Amsterdam: { it: "Amsterdam", en: "Amsterdam" },
    Vienna: { it: "Vienna", en: "Vienna" },
    Lisbona: { it: "Lisbona", en: "Lisbon" },
    Valencia: { it: "Valencia", en: "Valencia" },
    Madrid: { it: "Madrid", en: "Madrid" },
    Dublino: { it: "Dublino", en: "Dublin" },
    Bruxelles: { it: "Bruxelles", en: "Brussels" },
    Marrakech: { it: "Marrakech", en: "Marrakech" },
    Budapest: { it: "Budapest", en: "Budapest" },
    Bucarest: { it: "Bucarest", en: "Bucharest" },
    Varsavia: { it: "Varsavia", en: "Warsaw" },
    Cracovia: { it: "Cracovia", en: "Krakow" },
    Marsiglia: { it: "Marsiglia", en: "Marseille" },
    Edimburgo: { it: "Edimburgo", en: "Edinburgh" },
    California: { it: "California", en: "California" },
    Miami: { it: "Miami", en: "Miami" },
    Helsinki: { it: "Helsinki", en: "Helsinki" },
    Oslo: { it: "Oslo", en: "Oslo" },
    Amburgo: { it: "Amburgo", en: "Hamburg" },
    "Monaco di Baviera": { it: "Monaco di Baviera", en: "Munich" },
    Bangkok: { it: "Bangkok", en: "Bangkok" },
    "Los Angeles": { it: "Los Angeles", en: "Los Angeles" },
    "San Francisco": { it: "San Francisco", en: "San Francisco" },
    "L'Avana": { it: "L'Avana", en: "Havana" },
    Seoul: { it: "Seoul", en: "Seoul" },
    Kyoto: { it: "Kyoto", en: "Kyoto" },
    Osaka: { it: "Osaka", en: "Osaka" },
    Sydney: { it: "Sydney", en: "Sydney" },
    Melbourne: { it: "Melbourne", en: "Melbourne" },
    Reykjavik: { it: "Reykjavik", en: "Reykjavik" },
    Siviglia: { it: "Siviglia", en: "Seville" },
    Zagabria: { it: "Zagabria", en: "Zagreb" },
    Cairo: { it: "Cairo", en: "Cairo" },
    Atene: { it: "Atene", en: "Athens" },
    Sofia: { it: "Sofia", en: "Sofia" },
    Belgrado: { it: "Belgrado", en: "Belgrade" },
    Lubiana: { it: "Lubiana", en: "Ljubljana" },
    Bratislava: { it: "Bratislava", en: "Bratislava" },
    Tallinn: { it: "Tallinn", en: "Tallinn" },
    Riga: { it: "Riga", en: "Riga" },
    Vilnius: { it: "Vilnius", en: "Vilnius" },
    Lussemburgo: { it: "Lussemburgo", en: "Luxembourg" },
    "San Marino": { it: "San Marino", en: "San Marino" },
    Berna: { it: "Berna", en: "Bern" },
    Zurigo: { it: "Zurigo", en: "Zurich" },
    Ginevra: { it: "Ginevra", en: "Geneva" },
    Nizza: { it: "Nizza", en: "Nice" },
    Cannes: { it: "Cannes", en: "Cannes" },
    Bordeaux: { it: "Bordeaux", en: "Bordeaux" },
    Lione: { it: "Lione", en: "Lyon" },
    Porto: { it: "Porto", en: "Porto" },
    Faro: { it: "Faro", en: "Faro" },
    Bilbao: { it: "Bilbao", en: "Bilbao" },
    "Palma di Maiorca": { it: "Palma di Maiorca", en: "Palma de Mallorca" },
    Alicante: { it: "Alicante", en: "Alicante" },
    Malaga: { it: "Malaga", en: "Malaga" },
    "Gran Canaria": { it: "Gran Canaria", en: "Gran Canaria" },
    Fuerteventura: { it: "Fuerteventura", en: "Fuerteventura" },
    Creta: { it: "Creta", en: "Crete" },
    Rodi: { it: "Rodi", en: "Rhodes" },
    Spalato: { it: "Spalato", en: "Split" },
    Dubrovnik: { it: "Dubrovnik", en: "Dubrovnik" },
    Sarajevo: { it: "Sarajevo", en: "Sarajevo" }
  }
}